 

var fs = require('fs'); 
var pdfFillForm = require('pdf-fill-form');
var sourcePDF = "CoroonBlankPPR.pdf";


var fields = [ { name: 'For Admin use only',
    page: 0,
    value: '',
    id: 65536,
    type: 'text' },
  { name: 'REQ PO Conf Ref',
    page: 0,
    value: '',
    id: 65537,
    type: 'text' },
  { name: 'REQ PO Conf Ref_2',
    page: 0,
    value: '',
    id: 65538,
    type: 'text' },
  { name: 'REQ PO Conf Ref_3',
    page: 0,
    value: '',
    id: 65539,
    type: 'text' },
  { name: 'REQ PO Conf Ref_4',
    page: 0,
    value: '',
    id: 65540,
    type: 'text' },
  { name: 'Cost CenterRow1',
    page: 0,
    value: 'CC2272xxx',
    id: 65541,
    type: 'text' },
  { name: 'FundRow1',
    page: 0,
    value: '1703',
    id: 65542,
    type: 'text' },
  { name: 'ProgramRow1',
    page: 0,
    value: 'PG001112',
    id: 65543,
    type: 'text' },
  { name: 'PurposeRow1',
    page: 0,
    value: 'PP3002',
    id: 65544,
    type: 'text' },
  { name: 'GrantGiftRow1',
    page: 0,
    value: 'BG201192',
    id: 65545,
    type: 'text' },
  { name: 'Spend CategoryRow1',
    page: 0,
    value: '',
    id: 65546,
    type: 'text' },
  { name: 'Dollar AmountRow1',
    page: 0,
    value: '',
    id: 65547,
    type: 'text' },
  { name: 'Cost CenterRow2',
    page: 0,
    value: '',
    id: 65548,
    type: 'text' },
  { name: 'FundRow2', page: 0, value: '', id: 65549, type: 'text' },
  { name: 'ProgramRow2',
    page: 0,
    value: '',
    id: 65550,
    type: 'text' },
  { name: 'PurposeRow2',
    page: 0,
    value: '',
    id: 65551,
    type: 'text' },
  { name: 'GrantGiftRow2',
    page: 0,
    value: '',
    id: 65552,
    type: 'text' },
  { name: 'Spend CategoryRow2',
    page: 0,
    value: '',
    id: 65553,
    type: 'text' },
  { name: 'Dollar AmountRow2',
    page: 0,
    value: '',
    id: 65554,
    type: 'text' },
  { name: 'Cost CenterRow3',
    page: 0,
    value: '',
    id: 65555,
    type: 'text' },
  { name: 'FundRow3', page: 0, value: '', id: 65556, type: 'text' },
  { name: 'ProgramRow3',
    page: 0,
    value: '',
    id: 65557,
    type: 'text' },
  { name: 'PurposeRow3',
    page: 0,
    value: '',
    id: 65558,
    type: 'text' },
  { name: 'GrantGiftRow3',
    page: 0,
    value: '',
    id: 65559,
    type: 'text' },
  { name: 'Spend CategoryRow3',
    page: 0,
    value: '',
    id: 65560,
    type: 'text' },
  { name: 'Dollar AmountRow3',
    page: 0,
    value: '',
    id: 65561,
    type: 'text' },
  { name: 'Business Purpose',
    page: 0,
    value:
     'New 3D printer for Maker Hub to increase 3D printing capacity',
    id: 65562,
    type: 'text' },
  { name: 'Name of Vendor 1',
    page: 0,
    value: '',
    id: 65563,
    type: 'text' },
  { name: 'Vendor\'s Contact',
    page: 0,
    value: '',
    id: 65564,
    type: 'text' },
  { name: 'Vendor\'s Phone Number',
    page: 0,
    value: '',
    id: 65565,
    type: 'text' },
  { name: 'Vendor\'s Email',
    page: 0,
    value: '',
    id: 65566,
    type: 'text' },
  { name: 'Check Box1',
    page: 0,
    value: false,
    id: 65567,
    type: 'checkbox' },
  { name: 'Order NoRow1',
    page: 0,
    value: '',
    id: 65568,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow1',
    page: 0,
    value: '',
    id: 65569,
    type: 'text' },
  { name: 'PriceRow1', page: 0, value: '', id: 65570, type: 'text' },
  { name: 'QuantityRow1',
    page: 0,
    value: '',
    id: 65571,
    type: 'text' },
  { name: 'TotalRow1', page: 0, value: '0', id: 65572, type: 'text' },
  { name: 'Order NoRow2',
    page: 0,
    value: '',
    id: 65573,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow2',
    page: 0,
    value: '',
    id: 65574,
    type: 'text' },
  { name: 'PriceRow2', page: 0, value: '', id: 65575, type: 'text' },
  { name: 'QuantityRow2',
    page: 0,
    value: '',
    id: 65576,
    type: 'text' },
  { name: 'TotalRow02',
    page: 0,
    value: '0',
    id: 65577,
    type: 'text' },
  { name: 'Order NoRow3',
    page: 0,
    value: '',
    id: 65578,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow3',
    page: 0,
    value: '',
    id: 65579,
    type: 'text' },
  { name: 'PriceRow3', page: 0, value: '', id: 65580, type: 'text' },
  { name: 'QuantityRow3',
    page: 0,
    value: '',
    id: 65581,
    type: 'text' },
  { name: 'TotalRow03',
    page: 0,
    value: '0',
    id: 65582,
    type: 'text' },
  { name: 'Order NoRow4',
    page: 0,
    value: '',
    id: 65583,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow4',
    page: 0,
    value: '',
    id: 65584,
    type: 'text' },
  { name: 'PriceRow4', page: 0, value: '', id: 65585, type: 'text' },
  { name: 'QuantityRow4',
    page: 0,
    value: '',
    id: 65586,
    type: 'text' },
  { name: 'TotalRow04',
    page: 0,
    value: '0',
    id: 65587,
    type: 'text' },
  { name: 'Order NoRow5',
    page: 0,
    value: '',
    id: 65588,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow5',
    page: 0,
    value: '',
    id: 65589,
    type: 'text' },
  { name: 'PriceRow5', page: 0, value: '', id: 65590, type: 'text' },
  { name: 'QuantityRow5',
    page: 0,
    value: '',
    id: 65591,
    type: 'text' },
  { name: 'TotalRow05',
    page: 0,
    value: '0',
    id: 65592,
    type: 'text' },
  { name: 'Order NoRow6',
    page: 0,
    value: '',
    id: 65593,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow6',
    page: 0,
    value: '',
    id: 65594,
    type: 'text' },
  { name: 'PriceRow6', page: 0, value: '', id: 65595, type: 'text' },
  { name: 'QuantityRow6',
    page: 0,
    value: '',
    id: 65596,
    type: 'text' },
  { name: 'TotalRow06',
    page: 0,
    value: '0',
    id: 65597,
    type: 'text' },
  { name: 'Order NoRow7',
    page: 0,
    value: '',
    id: 65598,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow7',
    page: 0,
    value: '',
    id: 65599,
    type: 'text' },
  { name: 'PriceRow7', page: 0, value: '', id: 65600, type: 'text' },
  { name: 'QuantityRow7',
    page: 0,
    value: '',
    id: 65601,
    type: 'text' },
  { name: 'TotalRow07',
    page: 0,
    value: '0',
    id: 65602,
    type: 'text' },
  { name: 'Order NoRow8',
    page: 0,
    value: '',
    id: 65603,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow8',
    page: 0,
    value: '',
    id: 65604,
    type: 'text' },
  { name: 'PriceRow8', page: 0, value: '', id: 65605, type: 'text' },
  { name: 'QuantityRow8',
    page: 0,
    value: '',
    id: 65606,
    type: 'text' },
  { name: 'TotalRow08',
    page: 0,
    value: '0',
    id: 65607,
    type: 'text' },
  { name: 'Order NoRow9',
    page: 0,
    value: '',
    id: 65608,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow9',
    page: 0,
    value: '',
    id: 65609,
    type: 'text' },
  { name: 'PriceRow9', page: 0, value: '', id: 65610, type: 'text' },
  { name: 'QuantityRow9',
    page: 0,
    value: '',
    id: 65611,
    type: 'text' },
  { name: 'TotalRow09',
    page: 0,
    value: '0',
    id: 65612,
    type: 'text' },
  { name: 'Order NoRow10',
    page: 0,
    value: '',
    id: 65613,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow10',
    page: 0,
    value: '',
    id: 65614,
    type: 'text' },
  { name: 'PriceRow10', page: 0, value: '', id: 65615, type: 'text' },
  { name: 'QuantityRow10',
    page: 0,
    value: '',
    id: 65616,
    type: 'text' },
  { name: 'TotalRow10',
    page: 0,
    value: '0',
    id: 65617,
    type: 'text' },
  { name: 'Order NoRow11',
    page: 0,
    value: 'Order NoRow11',
    id: 65618,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow11',
    page: 0,
    value: 'row 11 description',
    id: 65619,
    type: 'text' },
  { name: 'PriceRow11', page: 0, value: 'PriceRow11', id: 65620, type: 'text' },
  { name: 'QuantityRow11',
    page: 0,
    value: 'QuantityRow11',
    id: 65621,
    type: 'text' },
  { name: 'TotalRow11',
    page: 0,
    value: 'TotalRow11',
    id: 65622,
    type: 'text' },
  { name: 'Order NoRow12',
    page: 0,
    value: '',
    id: 65623,
    type: 'text' },
  { name: 'ITEM NUMBER  DESCRIPTIONRow12',
    page: 0,
    value: '',
    id: 65624,
    type: 'text' },
  { name: 'PriceRow12', page: 0, value: '', id: 65625, type: 'text' },
  { name: 'QuantityRow12',
    page: 0,
    value: '',
    id: 65626,
    type: 'text' },
  { name: 'TotalRow12',
    page: 0,
    value: '0',
    id: 65627,
    type: 'text' },
  { name: 'TotalTOTAL', page: 0, value: '', id: 65628, type: 'text' },
  { name: 'Requestor\'s Print Name',
    page: 0,
    value: 'Don Undeen',
    id: 65629,
    type: 'text' },
  { name: 'Date', page: 0, value: '', id: 65630, type: 'text' },
  { name: 'Cost Center Approver Print Name',
    page: 0,
    value: '',
    id: 65631,
    type: 'text' },
  { name: 'Date_2', page: 0, value: '', id: 65632, type: 'text' } ];



var newfields = {
	"TotalRow09":"TotalRow09Val",
	"TotalRow08":"TotalRow08Val"}


doWrite(newfields);




function doRead(){
	pdfFillForm.read(sourcePDF)
	.then(function(result) {
	    console.log(result);
	}, function(err) {
	    console.log(err);
	});
}

function doWrite(fields){
	pdfFillForm.write(sourcePDF, fields, { "save": "pdf", 'cores': 4, 'scale': 0.2, 'antialias': true } )
	.then(function(result) {
	    fs.writeFile("test123.pdf", result, function(err) {
	        if(err) {
	       		return console.log(err);
	       	}
	       	console.log("The file was saved!");
	    }); 
	}, function(err) {
	  	console.log(err);
	});
}